RIESGOS Y RESPUESTAS/Controllers/Activoes1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RIESGOS_Y_RESPUESTAS.Models;

namespace RIESGOS_Y_RESPUESTAS.Controllers
{
    public class Activoes1Controller : Controller
    {
        private readonly DbgestorContext _context;

        public Activoes1Controller(DbgestorContext context)
        {
            _context = context;
        }

        // GET: Activoes1
        public async Task<IActionResult> Index()
        {
            var dbgestorContext = _context.Activos.Include(a => a.IdmunicipalidadNavigation);
            var items = _context.Activos.Include(a => a.Dañosformularios).ToList();
            return View(await dbgestorContext.ToListAsync());
        }

        // GET: Activoes1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activo = await _context.Activos
                .Include(a => a.IdmunicipalidadNavigation)
                .Include(a => a.Dañosformularios)
                .FirstOrDefaultAsync(m => m.Idactivos == id);

            if (activo == null)
            {
                return NotFound();
            }

            return View(activo);
        }

    
        // GET: Activoes1/Create
        public IActionResult Create()
        {
            ViewData["Idmunicipalidad"] = new SelectList(_context.MunicipalidadIqqs, "Idmunicipalidad", "NombreDepartamento");
            return View();
        }

        // POST: Activoes1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // POST: Activoes1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Idactivos,Implementos,TiposDeActivosIdtipos,CosteActivos,Cantidad,Idmunicipalidad")] Activo activo)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(activo);
                    await _context.SaveChangesAsync();
                    TempData["SuccessMessage"] = "El registro se ha guardado correctamente.";
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException ex)
                {
                    ModelState.AddModelError("", "No se pudo guardar el activo. Inténtalo de nuevo. Detalles del error: " + ex.Message);
                }
                finally
                {
                    activo = null;
                }
            }

            // Si llegamos aquí, es porque hubo un error de validación o una excepción
            ViewData["Idmunicipalidad"] = new SelectList(_context.MunicipalidadIqqs, "Idmunicipalidad", "NombreDepartamento", activo.Idmunicipalidad);
            return View(activo);
        }
        // GET: Activoes1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activo = await _context.Activos.FindAsync(id);
            if (activo == null)
            {
                return NotFound();
            }
            ViewData["Idmunicipalidad"] = new SelectList(_context.MunicipalidadIqqs, "Idmunicipalidad", "NombreDepartamento", activo.Idmunicipalidad);
            return View(activo);
        }

        // POST: Activoes1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Idactivos,Implementos,TiposDeActivosIdtipos,CosteActivos,Cantidad,Idmunicipalidad")] Activo activo)
        {
            if (id != activo.Idactivos)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(activo);
                    TempData["SuccessMessage"] = "El registro se ha modificado exitosamente.";
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActivoExists(activo.Idactivos))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Idmunicipalidad"] = new SelectList(_context.MunicipalidadIqqs, "Idmunicipalidad", "NombreDepartamento", activo.Idmunicipalidad);
            return View(activo);
        }

        // GET: Activoes1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activo = await _context.Activos
                .Include(a => a.IdmunicipalidadNavigation)
                .FirstOrDefaultAsync(m => m.Idactivos == id);
            if (activo == null)
            {
                return NotFound();
            }

            return View(activo);
        }

        // POST: Activoes1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var activo = await _context.Activos.FindAsync(id);
            if (activo == null)
            {
                return NotFound();
            }

            try
            {
                _context.Activos.Remove(activo);
                await _context.SaveChangesAsync();
                TempData["SuccessMessage"] = "El registro se ha eliminado exitosamente.";
                return RedirectToAction(nameof(Index)); // Redirigir al índice si la eliminación fue exitosa
            }
            catch (DbUpdateException)
            {
                // Guardar un mensaje y el ID del activo en TempData si no se puede eliminar
                TempData["ErrorMessage"] = "No se puede eliminar este activo porque está relacionado con otros registros.";
                TempData["ErrorActivoId"] = id; // Guarda el ID del activo
                return RedirectToAction(nameof(Delete), new { id }); // Redirigir a la vista de eliminación con el ID del activo
            }
        }

        private bool ActivoExists(int id)
        {
            return _context.Activos.Any(e => e.Idactivos == id);
        }
    }
}

RIESGOS Y RESPUESTAS/Controllers/DañosformularioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RIESGOS_Y_RESPUESTAS.Models;

namespace RIESGOS_Y_RESPUESTAS.Controllers
{
    public class DañosformularioController : Controller
    {
        private readonly DbgestorContext _context;

        public DañosformularioController(DbgestorContext context)
        {
            _context = context;
        }

        // GET: Dañosformulario
        public async Task<IActionResult> Index()
        {
            var dbgestorContext = _context.Dañosformularios.Include(d => d.ActivosNavigation);
            return View(await dbgestorContext.ToListAsync());
        }

        // GET: Dañosformulario/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dañosformulario = await _context.Dañosformularios
                .Include(d => d.ActivosNavigation)
                .FirstOrDefaultAsync(m => m.Iddañosimportantes == id);
            if (dañosformulario == null)
            {
                return NotFound();
            }

            return View(dañosformulario);
        }

        // GET: Dañosformulario/Create
        public IActionResult Create()
        {
            ViewData["Activos"] = new SelectList(_context.Activos, "Idactivos", "Implementos");
            return View();
        }

        // POST: Dañosformulario/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Iddañosimportantes,AreasAfectadas,ValorDaños,Respuesta,Activos,EstadoDaño")] Dañosformulario dañosformulario)
        {
            try
            {
                // Verificar si ya existen los mismos datos en la base de datos
                bool datosDuplicados = await _context.Dañosformularios.AnyAsync(df =>
                    //df.AreasAfectadas == dañosformulario.AreasAfectadas &&
                    df.ValorDaños == dañosformulario.ValorDaños &&
                    df.Respuesta == dañosformulario.Respuesta &&
                    df.Activos == dañosformulario.Activos &&
                    df.EstadoDaño == dañosformulario.EstadoDaño
                );

                if (datosDuplicados)
                {
                    ModelState.AddModelError("", "Ya existe un registro con los mismos datos. ingrese al dato ya existente en editar y modificar si es necesario");
                }
                // Validación personalizada
                //if (string.IsNullOrEmpty(dañosformulario.AreasAfectadas))
                //{
                //    ModelState.AddModelError(nameof(dañosformulario.AreasAfectadas), "Las áreas afectadas son obligatorias.");
                //}
                if (string.IsNullOrEmpty(dañosformulario.ValorDaños))
                {
                    ModelState.AddModelError(nameof(dañosformulario.ValorDaños), "El valor de daños es obligatorio.");
                }
                if (!dañosformulario.Activos.HasValue)
                {
                    ModelState.AddModelError(nameof(dañosformulario.Activos), "El ID de activos es obligatorio.");
                }
                if (!dañosformulario.Respuesta.HasValue)
                {
                    ModelState.AddModelError(nameof(dañosformulario.Respuesta), "La respuesta es obligatoria.");
                }
                if (string.IsNullOrEmpty(dañosformulario.EstadoDaño))
                {
                    ModelState.AddModelError(nameof(dañosformulario.EstadoDaño), "El estado del daño es obligatorio.");
                }
                if (ModelState.IsValid)
                {
                    _context.Add(dañosformulario);
                    await _context.SaveChangesAsync();
                    TempData["SuccessMessage"] = "El registro se ha guardado exitosamente.";
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException ex)
            {
                ModelState.AddModelError("", "No se pudo guardar el activo. Inténtalo de nuevo. Detalles del error: " + ex.Message);
            }

            // Cargar datos para la vista en caso de error
            ViewData["Activos"] = new SelectList(_context.Activos, "Idactivos", "Implementos", dañosformulario.Activos);
            return View(dañosformulario);
        }

        // GET: Dañosformulario/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dañosformulario = await _context.Dañosformularios.FindAsync(id);
            if (dañosformulario == null)
            {
                return NotFound();
            }
            ViewData["Activos"] = new SelectList(_context.Activos, "Idactivos", "Implementos", dañosformulario.Activos);
            return View(dañosformulario);
        }

        // POST: Dañosformulario/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Iddañosimportantes,AreasAfectadas,ValorDaños,Respuesta,Activos,EstadoDaño")] Dañosformulario dañosformulario)
        {
            // Lógica de validación...

            if (id != dañosformulario.Iddañosimportantes)
            {
                return NotFound();
            }

            var existingEntity = await _context.Dañosformularios.FindAsync(id);
            if (existingEntity == null)
            {
                return NotFound();
            }
            // Verificar si los datos son los mismos que los actuales
            var existingDañosformulario = await _context.Dañosformularios.FindAsync(id);
            if (existingDañosformulario != null)
            {
                bool isSameData =
                    existingDañosformulario.AreasAfectadas == dañosformulario.AreasAfectadas &&
                    existingDañosformulario.ValorDaños == dañosformulario.ValorDaños &&
                    existingDañosformulario.Respuesta == dañosformulario.Respuesta &&
                    existingDañosformulario.Activos == dañosformulario.Activos &&
                    existingDañosformulario.EstadoDaño == dañosformulario.EstadoDaño;

                if (isSameData)
                {
                    ModelState.AddModelError("", "No se realizaron cambios; los datos son los mismos que los existentes.");
                }
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Entry(existingEntity).CurrentValues.SetValues(dañosformulario);
                    TempData["SuccessMessage"] = "El registro se ha modificado correctamente";
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DañosformularioExists(dañosformulario.Iddañosimportantes))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["Activos"] = new SelectList(_context.Activos, "Idactivos", "Implementos", dañosformulario.Activos);
            return View(dañosformulario);
        }

        // GET: Dañosformulario/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dañosformulario = await _context.Dañosformularios
                .Include(d => d.ActivosNavigation)
                .FirstOrDefaultAsync(m => m.Iddañosimportantes == id);
            if (dañosformulario == null)
            {
                return NotFound();
            }

            return View(dañosformulario);
        }

        // POST: Dañosformulario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dañosformulario = await _context.Dañosformularios.FindAsync(id);
            if (dañosformulario != null)
            {
                _context.Dañosformularios.Remove(dañosformulario);
            }

            await _context.SaveChangesAsync();
            TempData["SuccessMessage"] = "El registro se ha eliminado exitosamente.";
            return RedirectToAction(nameof(Index));
        }

        private bool DañosformularioExists(int id)
        {
            return _context.Dañosformularios.Any(e => e.Iddañosimportantes == id);
        }
    }
}

RIESGOS Y RESPUESTAS/Views/Activoes1/Create.cshtml
@model RIESGOS_Y_RESPUESTAS.Models.Activo

@{
    ViewData["Title"] = "Create";
}


<h1 class="text-center mt-4">Registro de Activos Nuevos</h1>
<hr />
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
            <div class="card shadow-lg rounded-4 border-0">
                <div class="card-body p-5">
                    <h2 class="text-center mb-4">Crear Nuevo Registro de Activos</h2>

                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <!--implementos-->
                        <div class="mb-3">
                            <div class="form-group mb-4 position-relative">
                                <label asp-for="Implementos" class="form-label">Implementos <i class="bi bi-tools"></i></label>
                                <div class="input-group">
                                    <span class="input-group-text bg-light"><i class="bi bi-tools"></i></span>
                                    <input asp-for="Implementos" class="form-control" placeholder="Ingresa los implementos" />
                                </div>
                                <span asp-validation-for="Implementos" class="text-danger"></span>
                            </div>
                        </div>

                        <!--tipo de activo-->
                        <div class="mb-3">
                            <div class="form-group mb-4 position-relative">
                                <label asp-for="TiposDeActivosIdtipos" class="form-label">Tipo de Activo <i class="bi bi-file-earmark-text"></i></label>
                                <div class="input-group">
                                    <span class="input-group-text bg-light"><i class="bi bi-file-earmark-text"></i></span>
                                    <input asp-for="TiposDeActivosIdtipos" class="form-control" placeholder="Ingresa el tipo de activo" />
                                </div>
                                <span asp-validation-for="TiposDeActivosIdtipos" class="text-danger"></span>
                            </div>
                        </div>

                        <!--coste activo-->
                        <div class="mb-3">
                            <div class="form-group mb-4 position-relative">
                                <label asp-for="CosteActivos" class="form-label fw-bold">Coste del Activo <i class="bi bi-cash"></i></label>
                                <div class="input-group">
                                    <span class="input-group-text bg-light"><i class="bi bi-cash"></i></span>
                                    <input asp-for="CosteActivos" class="form-control" placeholder="Ingresa el coste del activo"
                                           type="number" step="0.01" min="0" />
                                </div>
                                <span asp-validation-for="CosteActivos" class="text-danger"></span>
                            </div>
                        </div>

                        <!--cantidad-->
                        <div class="mb-3">
                            <div class="form-group mb-4 position-relative">
                                <label asp-for="Cantidad" class="form-label fw-bold">Cantidad <i class="bi bi-box"></i></label>
                                <div class="input-group">
                                    <span class="input-group-text bg-light"><i class="bi bi-box"></i></span>
                                    <input asp-for="Cantidad" class="form-control" placeholder="Ingresa la cantidad" />
                                </div>
                                <span asp-validation-for="Cantidad" class="text-danger"></span>
                            </div>
                        </div>

                         <!--municipalidad-->
                        <div class="mb-3">
                            <div class="form-group mb-4 position-relative">
                                <label asp-for="Idmunicipalidad" class="form-label fw-bold">Municipalidad <i class="bi bi-house"></i></label>
                                <div class="input-group">
                                    <span class="input-group-text bg-light"><i class="bi bi-house"></i></span>
                                    <select asp-for="Idmunicipalidad" class="form-select" asp-items="ViewBag.Idmunicipalidad">
                                        <option value="" disabled selected>Selecciona una municipalidad</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <!-- Botones -->
                        <div class="text-center mt-4">
                            <input type="submit" value="Crear Registro" class="btn btn-success btn-lg me-2" 
                               onclick="return confirm('Por favor, revise los datos ingresados. Si son correctos, haga clic en Aceptar para guardarlos. Si necesita hacer cambios, haga clic en Cancelar .');" />
                            <a asp-action="Index" class="btn btn-secondary btn-lg"
                               onclick="return confirm('¿Estás seguro de que deseas volver a la lista?');">Volver a la Lista</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="back-to-home-container">
    <a asp-controller="Home" asp-action="Index" class="btn-custom">
        <i class="fas fa-home align-content-center"></i> Volver a Inicio
    </a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

RIESGOS Y RESPUESTAS/Views/Activoes1/Delete.cshtml
@model RIESGOS_Y_RESPUESTAS.Models.Activo

@{
    ViewData["Title"] = "Delete";
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger mt-3">
        <strong>Error:</strong> @TempData["ErrorMessage"]
        @if (TempData["ErrorActivoId"] != null)
        {
            <div class="mt-2">
                <a asp-action="Details" asp-route-id="@TempData["ErrorActivoId"]" class="btn btn-warning">
                    <i class="fas fa-eye"></i> Ver Detalles
                </a>
            </div>
        }
    </div>
}

<div>
    <h1 class="text-danger text-center"><i class="fas fa-trash-alt"></i> Eliminar Activo</h1>
</div>
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="card shadow-lg rounded-4 border-0">
            <h3 class="mb-4">¿Seguro que desea eliminar los datos seleccionados?</h3>
            <div>
                <h4>Detalles del Activo</h4>
                <hr />
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Implementos)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Implementos)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.TiposDeActivosIdtipos)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.TiposDeActivosIdtipos)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.CosteActivos)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.CosteActivos)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Cantidad)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Cantidad)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.IdmunicipalidadNavigation.NombreDepartamento)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.IdmunicipalidadNavigation.NombreDepartamento)
                    </dd>
                </dl>

                <form method="post" asp-action="Delete" asp-route-id="@Model.Idactivos">
                    <input type="hidden" asp-for="Idactivos" />
                    <div class="text-center">
                        <button type="submit" class="btn btn-danger btn-lg" onclick="return confirm('¿Seguro que quieres eliminar esto? Esta acción no se puede deshacer.');">
                            <i class="fas fa-trash"></i> Eliminar
                        </button>
                        <a asp-action="Index" class="btn btn-secondary btn-lg ms-2">
                            <i class="fas fa-arrow-left"></i> Volver a la Lista
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

RIESGOS Y RESPUESTAS/Views/Activoes1/Details.cshtml
@model RIESGOS_Y_RESPUESTAS.Models.Activo

@{
    ViewData["Title"] = "Details";
}


<div class="container my-5">
    <h1 class="my-4 text-center">Detalles del Activo</h1>
    <div class="card shadow-lg p-4">
        <div class="card-body">
            <h4 class="card-title mb-4">
                <i class="fas fa-info-circle me-2"></i> Información del Activo
            </h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-3 fw-bold">
                    <i class="fas fa-tools me-2"></i> @Html.DisplayNameFor(model => model.Implementos)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Implementos)
                </dd>

                <dt class="col-sm-3 fw-bold">
                    <i class="fas fa-box-open me-2"></i> @Html.DisplayNameFor(model => model.TiposDeActivosIdtipos)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.TiposDeActivosIdtipos)
                </dd>

                <dt class="col-sm-3 fw-bold">
                    <i class="fas fa-dollar-sign me-2"></i> @Html.DisplayNameFor(model => model.CosteActivos)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.CosteActivos)
                </dd>

                <dt class="col-sm-3 fw-bold">
                    <i class="fas fa-sort-numeric-up me-2"></i> @Html.DisplayNameFor(model => model.Cantidad)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Cantidad)
                </dd>

                <dt class="col-sm-3 fw-bold">
                    <i class="fas fa-map-marker-alt me-2"></i> @Html.DisplayNameFor(model => model.IdmunicipalidadNavigation.NombreDepartamento)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.IdmunicipalidadNavigation.NombreDepartamento)
                </dd>

                <dd class="col-sm-9 night-mode">
                    <p class="card-text text-secondary fst-italic">Reportado desde el formulario de daños:</p>
                    @if (Model.Dañosformularios.Any())
                    {
                        <div class="row">
                            @foreach (var dañosformulario in Model.Dañosformularios)
                            {
                                <div class="col-md-6 mb-3">
                                    <div class="card border-info shadow-sm">
                                        <div class="card-body">
                                            <h5 class="card-title">Áreas Afectadas: @dañosformulario.AreasAfectadas</h5>
                                            <p class="card-text">Codigo De Formulario: @dañosformulario.Iddañosimportantes</p>
                                            <!-- Enlace para ver los detalles del formulario de daños -->
                                            <a asp-action="Details" asp-controller="Dañosformulario" asp-route-id="@dañosformulario.Iddañosimportantes" class="btn btn-primary btn-sm">
                                                <!-- Icono para representar la acción de "Ver Detalles" (Font Awesome) -->
                                                <i class="fas fa-info-circle me-1"></i> Ver Detalles
                                            </a>
                                            
                                            <!-- Enlace para editar el formulario de daños -->
                                            <a asp-action="Edit" asp-controller="Dañosformulario" asp-route-id="@dañosformulario.Iddañosimportantes" class="btn btn-primary btn-sm">
                                                <!-- Icono para representar la acción de "Editar" (Font Awesome) -->
                                                <i class="fas fa-edit me-1"></i> Editar
                                            </a>

                                            <!-- Enlace para eliminar el formulario de daños -->
                                            <a asp-action="Delete" asp-controller="Dañosformulario" asp-route-id="@dañosformulario.Iddañosimportantes" class="btn btn-danger btn-sm"
                                               onclick="return confirm('¿Estás seguro de que deseas eliminar esta área afectada?');">
                                                <!-- Icono para representar la acción de "Eliminar" (Font Awesome) -->
                                                <i class="fas fa-trash-alt me-1"></i> Eliminar
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    }
                    else
                    {
                        <p class="text-success fst-italic">No hay daños reportados.</p>
                    }
                </dd>
            </dl>
        </div>
    </div>

    <div class="mt-4 text-center">
        <a asp-action="Edit" asp-route-id="@Model?.Idactivos" class="btn btn-primary">
            <i class="fas fa-edit me-2"></i> Editar
        </a>
        <a asp-action="Index" class="btn btn-secondary">
            <i class="fas fa-arrow-left me-2"></i> Volver a la lista
        </a>
    </div>
</div>