RIESGOS Y RESPUESTAS/Controllers/Activoes1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RIESGOS_Y_RESPUESTAS.Models;

namespace RIESGOS_Y_RESPUESTAS.Controllers
{
    public class Activoes1Controller : Controller
    {
        private readonly DbgestorContext _context;

        public Activoes1Controller(DbgestorContext context)
        {
            _context = context;
        }

        // GET: Activoes1
        public async Task<IActionResult> Index()
        {
            var dbgestorContext = _context.Activos.Include(a => a.IdmunicipalidadNavigation);
            var items = _context.Activos.Include(a => a.Dañosformularios).ToList();
            return View(await dbgestorContext.ToListAsync());
        }

        // GET: Activoes1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activo = await _context.Activos
                .Include(a => a.IdmunicipalidadNavigation)
                .Include(a => a.Dañosformularios)
                .FirstOrDefaultAsync(m => m.Idactivos == id);

            if (activo == null)
            {
                return NotFound();
            }

            return View(activo);
        }

    
        // GET: Activoes1/Create
        public IActionResult Create()
        {
            ViewData["Idmunicipalidad"] = new SelectList(_context.MunicipalidadIqqs, "Idmunicipalidad", "NombreDepartamento");
            return View();
        }

        // POST: Activoes1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // POST: Activoes1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Idactivos,Implementos,TiposDeActivosIdtipos,CosteActivos,Cantidad,Idmunicipalidad")] Activo activo)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(activo);
                    await _context.SaveChangesAsync();
                    TempData["SuccessMessage"] = "El registro se ha guardado correctamente.";
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException ex)
                {
                    ModelState.AddModelError("", "No se pudo guardar el activo. Inténtalo de nuevo. Detalles del error: " + ex.Message);
                }
                finally
                {
                    activo = null;
                }
            }

            // Si llegamos aquí, es porque hubo un error de validación o una excepción
            ViewData["Idmunicipalidad"] = new SelectList(_context.MunicipalidadIqqs, "Idmunicipalidad", "NombreDepartamento", activo.Idmunicipalidad);
            return View(activo);
        }
        // GET: Activoes1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activo = await _context.Activos.FindAsync(id);
            if (activo == null)
            {
                return NotFound();
            }
            ViewData["Idmunicipalidad"] = new SelectList(_context.MunicipalidadIqqs, "Idmunicipalidad", "NombreDepartamento", activo.Idmunicipalidad);
            return View(activo);
        }

        // POST: Activoes1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Idactivos,Implementos,TiposDeActivosIdtipos,CosteActivos,Cantidad,Idmunicipalidad")] Activo activo)
        {
            if (id != activo.Idactivos)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(activo);
                    TempData["SuccessMessage"] = "El registro se ha modificado exitosamente.";
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActivoExists(activo.Idactivos))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Idmunicipalidad"] = new SelectList(_context.MunicipalidadIqqs, "Idmunicipalidad", "NombreDepartamento", activo.Idmunicipalidad);
            return View(activo);
        }

        // GET: Activoes1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activo = await _context.Activos
                .Include(a => a.IdmunicipalidadNavigation)
                .FirstOrDefaultAsync(m => m.Idactivos == id);
            if (activo == null)
            {
                return NotFound();
            }

            return View(activo);
        }

        // POST: Activoes1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var activo = await _context.Activos.FindAsync(id);
            if (activo == null)
            {
                return NotFound();
            }

            try
            {
                _context.Activos.Remove(activo);
                await _context.SaveChangesAsync();
                TempData["SuccessMessage"] = "El registro se ha eliminado exitosamente.";
                return RedirectToAction(nameof(Index)); // Redirigir al índice si la eliminación fue exitosa
            }
            catch (DbUpdateException)
            {
                // Guardar un mensaje y el ID del activo en TempData si no se puede eliminar
                TempData["ErrorMessage"] = "No se puede eliminar este activo porque está relacionado con otros registros.";
                TempData["ErrorActivoId"] = id; // Guarda el ID del activo
                return RedirectToAction(nameof(Delete), new { id }); // Redirigir a la vista de eliminación con el ID del activo
            }
        }

        private bool ActivoExists(int id)
        {
            return _context.Activos.Any(e => e.Idactivos == id);
        }
    }
}

RIESGOS Y RESPUESTAS/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RIESGOS_Y_RESPUESTAS.Models;
using System.Diagnostics;

namespace RIESGOS_Y_RESPUESTAS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Authorize(Roles = "Administrador,Usuario")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Usuario")]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RIESGOS Y RESPUESTAS/Controllers/RiesgoesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RIESGOS_Y_RESPUESTAS.Models;

namespace RIESGOS_Y_RESPUESTAS.Controllers
{
    public class RiesgoesController : Controller
    {
        private readonly DbgestorContext _context;

        public RiesgoesController(DbgestorContext context)
        {
            _context = context;
        }

        // GET: Riesgoes
        public async Task<IActionResult> Index()
        {
            var dbgestorContext = _context.Riesgos.Include(r => r.AreaMunicipalidadNavigation);
            return View(await dbgestorContext.ToListAsync());
        }

        // GET: Riesgoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var riesgo = await _context.Riesgos
                .Include(r => r.AreaMunicipalidadNavigation)
                //.Include(r=> r.AreaMunicipalidad)error aca
                .FirstOrDefaultAsync(m => m.Idreportes == id);
            if (riesgo == null)
            {
                return NotFound();
            }

            var viewModel = new
            {
                Riesgo = riesgo,
                NivelAmenaza = riesgo.GetNivelAmenazaDescription() // Adjust if method is elsewhere
            };

            return View(riesgo);
        }

        // GET: Riesgoes/Create
        public IActionResult Create()
        {
            ViewData["AreaMunicipalidad"] = new SelectList(_context.MunicipalidadIqqs, "Idmunicipalidad", "NombreDepartamento");
            return View();
        }

        // POST: Riesgoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Idreportes,Nombre,NivelAmenaza,Detalles,AreaMunicipalidad,Daños,EstadoRiesgo,TipoRiesgo,Impacto,NivelAmenazaCopy1,ImpactoDescripcion,ImpactoNumerico")] Riesgo riesgo)
        {
            Debug.WriteLine("Inicio del método Create");

            try
            {
                // Verificar si ya existen los mismos datos en la base de datos
                bool datosDuplicados = await _context.Riesgos.AnyAsync(r =>
                    r.Nombre == riesgo.Nombre &&
                    r.NivelAmenaza == riesgo.NivelAmenaza &&
                    r.Detalles == riesgo.Detalles &&
                    r.AreaMunicipalidad == riesgo.AreaMunicipalidad &&
                    r.Daños == riesgo.Daños &&
                    r.EstadoRiesgo == riesgo.EstadoRiesgo &&
                    r.Impacto == riesgo.Impacto
                );

                Debug.WriteLine("Verificación de duplicados completada: " + datosDuplicados);

                if (datosDuplicados)
                {
                    ModelState.AddModelError("", "Ya existe un registro con los mismos datos. Por favor, edite el registro existente si es necesario.");
                    return View(riesgo);
                }

                // Ahora verifica la validación del ModelState
                if (!ModelState.IsValid)
                {
                    Debug.WriteLine("ModelState no es válido, revisando errores...");
                    foreach (var modelStateEntry in ModelState)
                    {
                        foreach (var error in modelStateEntry.Value.Errors)
                        {
                            Console.WriteLine($"Error en {modelStateEntry.Key}: {error.ErrorMessage}");
                        }
                    }
                    ViewBag.AreaMunicipalidad = new SelectList(_context.MunicipalidadIqqs, "Idmunicipalidad", "NombreDepartamento", riesgo.AreaMunicipalidad);
                    return View(riesgo);
                }

                // Si ModelState es válido, agrega el nuevo riesgo
                _context.Add(riesgo);
                await _context.SaveChangesAsync();

                // Agregar el mensaje a TempData
                TempData["SuccessMessage"] = "El registro se ha guardado correctamente.";
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException ex)
            {
                ModelState.AddModelError("", "No se pudo guardar el riesgo. Inténtalo de nuevo. Detalles del error: " + ex.Message);
                Debug.WriteLine("Error al guardar en la base de datos: " + ex.Message);
            }

            Debug.WriteLine("Se produjo un error al intentar guardar el registro.");

            // Si ocurre un error, vuelve a cargar la vista con el ViewBag y los datos actuales
            ViewBag.AreaMunicipalidad = new SelectList(_context.MunicipalidadIqqs, "Idmunicipalidad", "NombreDepartamento", riesgo.AreaMunicipalidad);
            return View(riesgo);
        }

        // GET: Riesgoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var model = _context.Riesgos.Find(id); // Adjust according to how you fetch data
            ViewBag.TipoRiesgoOptions = new SelectList(new[]
            {
            new { Value = "naturales", Text = "Amenazas Naturales" },
            new { Value = "humanas", Text = "Amenazas Humanas" },
            new { Value = "tecnologicas", Text = "Amenazas Tecnológicas" },
            new { Value = "organizativas", Text = "Amenazas Organizativas" },
            new { Value = "externas", Text = "Amenazas Externas" },
            new { Value = "internas", Text = "Amenazas Internas" },
            new { Value = "entorno", Text = "Amenazas Relacionadas con el Entorno" }
            }, "Value", "Text", model.TipoRiesgo);


            if (id == null)
            {
                return NotFound();
            }

            var riesgo = await _context.Riesgos.FindAsync(id);
            
            if (riesgo == null)
            {
                return NotFound();
            }
            ViewData["AreaMunicipalidad"] = new SelectList(_context.MunicipalidadIqqs, "Idmunicipalidad", "NombreDepartamento", riesgo.AreaMunicipalidad);
            return View(riesgo);
        }

        // POST: Riesgoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Idreportes,Nombre,Causantes,NivelAmenaza,Detalles,AreaMunicipalidad,Daños,EstadoRiesgo,TipoRiesgo,Impacto,NivelAmenazaCopy1,ImpactoDescripcion,ImpactoNumerico")] Riesgo riesgo)
        {
            if (id != riesgo.Idreportes)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Verificar si 'Detalles' está vacío
                if (string.IsNullOrWhiteSpace(riesgo.Detalles))
                {
                    ModelState.AddModelError(nameof(riesgo.Detalles), "El Detalle es obligatorio.");
                    return View(riesgo); // Retorna la vista con el mensaje de error
                }

                try
                {
                    _context.Update(riesgo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RiesgoExists(riesgo.Idreportes))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewData["AreaMunicipalidad"] = new SelectList(_context.MunicipalidadIqqs, "Idmunicipalidad", "Idmunicipalidad", riesgo.AreaMunicipalidad);
                TempData["SuccessMessage"] = "El registro se ha modificado exitosamente.";
                return RedirectToAction(nameof(Index));
            }
            return View(riesgo);
        }

        // GET: Riesgoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var riesgo = await _context.Riesgos
                .Include(r => r.AreaMunicipalidadNavigation)
                .FirstOrDefaultAsync(m => m.Idreportes == id);
            if (riesgo == null)
            {
                return NotFound();
            }

            return View(riesgo);
        }

        // POST: Riesgoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var riesgo = await _context.Riesgos.FindAsync(id);
            if (riesgo != null)
            {
                _context.Riesgos.Remove(riesgo);
            }

            await _context.SaveChangesAsync();
            TempData["SuccessMessage"] = "El registro se ha eliminado exitosamente.";
            return RedirectToAction(nameof(Index));
        }

        private bool RiesgoExists(int id)
        {
            return _context.Riesgos.Any(e => e.Idreportes == id);
        }
    }
}

RIESGOS Y RESPUESTAS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center container mt-5">
    <h1 class="display-4">gestor de riesgos - daños - respuesta</h1>
</div>
<hr />
<div class="container mt-5">
    <div class="text-center">
        <h1 class="mb-4">Seleccione un formulario</h1>
    </div>

    <div class="row justify-content-center mt-5">
        <!-- Card 1 -->
        <div class="col-md-4 mb-4">
            <div class="card shadow-lg h-100 border-0">
                <div class="card-body text-center">
                    <div class="icon mb-3">
                        <i class="fas fa-exclamation-triangle fa-3x text-warning"></i>
                    </div>
                    <h5 class="card-title">Formulario registro de riesgos</h5>
                    <p class="card-text">Completa el siguiente formulario para ingresar registro de riesgos.</p>
                    <a href="@Url.Action("Create", "Riesgoes")" class="btn btn-warning btn-block rounded-pill">Ir al Formulario de riesgos</a>
                </div>
            </div>
        </div>

        <!-- Card 4 -->
        <div class="col-md-4 mb-4">
            <div class="card shadow-lg h-100 border-0">
                <div class="card-body text-center">
                    <div class="icon mb-3">
                        <i class="fas fa-warehouse fa-3x text-primary"></i>
                    </div>
                    <h5 class="card-title">Formulario registro de activos</h5>
                    <p class="card-text">Completa el formulario para el ingreso de activos.</p>
                    <a href="@Url.Action("Create", "Activoes1")" class="btn btn-primary btn-block rounded-pill">Ir al Formulario de Activos</a>
                </div>
            </div>
        </div>

        <!-- Card 2 -->
        <div class="col-md-4 mb-4">
            <div class="card shadow-lg h-100 border-0">
                <div class="card-body text-center">
                    <div class="icon mb-3">
                        <i class="fas fa-bomb fa-3x text-danger"></i>
                    </div>
                    <h5 class="card-title">Formulario registro de daños</h5>
                    <p class="card-text">Completa el siguiente formulario para ingresar registro de daños.</p>
                    <a href="@Url.Action("Create", "DañosFormulario")" class="btn btn-danger btn-block rounded-pill">Ir al Formulario de Daños</a>
                </div>
            </div>
        </div>

        <!-- Card 3 -->
        <div class="col-md-4 mb-4">
            <div class="card shadow-lg h-100 border-0">
                <div class="card-body text-center">
                    <div class="icon mb-3">
                        <i class="fas fa-hand-holding-medical fa-3x text-success"></i>
                    </div>
                    <h5 class="card-title">Formulario registro de respuestas</h5>
                    <p class="card-text">Completa el siguiente formulario para registrar respuestas ante daños o riesgos.</p>
                    <a href="@Url.Action("Create", "Respuestums")" class="btn btn-success btn-block rounded-pill">Ir al Formulario de Respuestas</a>
                </div>
            </div>
        </div>
    </div>
</div>
<hr />
<div class="text-center">
    <h1 class="mb-4">Gráficos</h1>
</div>

<div class="container mt-5">
    <div class="row justify-content-center">
        <!-- Tarjeta para el gráfico de daños -->
        <div class="col-md-4 mb-4">
            <div class="card shadow-lg rounded-4 border-0">
                <div class="card-body text-center">
                    <h5 class="card-title"><i class="fas fa-chart-bar"></i> Gráfico de Daños</h5>
                    <p class="card-text">Visualiza los datos de daños registrados.</p>
                    <a href="@Url.Action("DamagesChart", "Graficos")" class="btn btn-danger">
                        <i class="fas fa-eye"></i> Ver Gráfico
                    </a>
                </div>
            </div>
        </div>

        <!-- Tarjeta para el gráfico de riesgos -->
        <div class="col-md-4 mb-4">
            <div class="card shadow-lg rounded-4 border-0">
                <div class="card-body text-center">
                    <h5 class="card-title"><i class="fas fa-chart-line"></i> Gráfico de Riesgos</h5>
                    <p class="card-text">Analiza los diferentes riesgos asociados.</p>
                    <a href="@Url.Action("RisksChart", "Graficos")" class="btn btn-warning">
                        <i class="fas fa-eye"></i> Ver Gráfico
                    </a>
                </div>
            </div>
        </div>

        <!-- Tarjeta para otro gráfico -->
        <div class="col-md-4 mb-4">
            <div class="card shadow-lg rounded-4 border-0">
                <div class="card-body text-center">
                    <h5 class="card-title"><i class="fas fa-chart-pie"></i> Gráfico Adicional</h5>
                    <p class="card-text">Explora otros datos relevantes.</p>
                    <a href="@Url.Action("AdditionalChart", "Graficos")" class="btn btn-secondary">
                        <i class="fas fa-eye"></i> Ver Gráfico
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>